server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  level:
   com.gy.dao: debug

spring:
  datasource:
    name: spike
    url: jdbc:mysql://127.0.0.1:3306/spike?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver